Vagrant.configure("2") do |config|
 
  config.vm.box = "rudolfochrist/ubuntu-desktop"
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "FSE-2011-CRYSTAL"
     vb.memory = "1024"
   end
 config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y openjdk-7-jdk
     sudo apt-get install -y openjdk-7-jre	 
     sudo apt-get install -y openjdk-7-jre-headless
 SHELL
end
